xiaoyaocz/dart_simple_live

assets/app_version.json, simple_live_app/ios/Podfile.lock, simple_live_app/ios/Runner.xcodeproj/project.pbxproj, simple_live_app/lib/main.dart, simple_live_app/lib/modules/live_room/live_room_controller.dart, simple_live_app/lib/modules/live_room/live_room_page.dart, simple_live_app/lib/modules/search/search_list_view.dart, simple_live_app/lib/modules/user/follow_user/follow_user_page.dart, simple_live_app/lib/modules/user/history/history_page.dart, simple_live_app/lib/requests/common_request.dart, simple_live_app/pubspec.lock, simple_live_app/pubspec.yaml, simple_live_core/example/simple_live_core_example.dart, simple_live_core/lib/src/bilibili_site.dart, simple_live_core/lib/src/douyu_site.dart, simple_live_core/lib/src/huya_site.dart, simple_live_core/lib/src/model/live_anchor_item.dart, simple_live_core/lib/src/model/live_category.dart, simple_live_core/lib/src/model/live_message.dart, simple_live_core/lib/src/model/live_play_quality.dart, simple_live_core/lib/src/model/live_room_detail.dart, simple_live_core/lib/src/model/live_room_item.dart
=> Release 1.1.0

README.md, assets/app_version.json, simple_live_app/lib/app/controller/app_settings_controller.dart, simple_live_app/lib/modules/live_room/live_room_controller.dart, simple_live_app/lib/modules/live_room/live_room_page.dart, simple_live_app/lib/modules/toolbox/toolbox_controller.dart, simple_live_app/lib/modules/toolbox/toolbox_page.dart, simple_live_app/lib/modules/user/auto_exit_settings_page.dart, simple_live_app/lib/modules/user/danmu_settings_page.dart, simple_live_app/lib/modules/user/user_page.dart, simple_live_app/lib/routes/app_pages.dart, simple_live_app/lib/routes/route_path.dart, simple_live_app/lib/services/local_storage_service.dart, simple_live_app/pubspec.lock, simple_live_app/pubspec.yaml, simple_live_console/bin/simple_live_console.dart, simple_live_core/example/simple_live_core_example.dart, simple_live_core/lib/src/common/web_socket_util.dart, simple_live_core/lib/src/danmaku/douyin_danmaku.dart, simple_live_core/lib/src/danmaku/proto/douyin.pb.dart, simple_live_core/lib/src/danmaku/proto/douyin.pbenum.dart, simple_live_core/lib/src/danmaku/proto/douyin.pbjson.dart, simple_live_core/lib/src/danmaku/proto/douyin.proto, simple_live_core/lib/src/douyin_site.dart, simple_live_core/pubspec.yaml
1. 支持抖音直播平台 (#1)
2. 新增定时关闭功能 (#23)
3. 修复iOS屏幕旋转问题 (#37)
=> Release 1.1.1

assets/app_version.json, simple_live_app/lib/app/controller/app_settings_controller.dart, simple_live_app/lib/modules/live_room/live_room_controller.dart, simple_live_app/lib/modules/live_room/live_room_page.dart, simple_live_app/pubspec.yaml, simple_live_core/lib/src/bilibili_site.dart
1. 修复进入后台自动暂停#89，#88，#85，#77
2. 哔哩哔哩优选非PCDN链接
3. 修复弹幕描边设置不生效 #81
=> Release 1.2.2

assets/app_version.json, simple_live_app/android/app/build.gradle, simple_live_app/lib/app/event_bus.dart, simple_live_app/lib/modules/category/category_controller.dart, simple_live_app/lib/modules/category/category_list_view.dart, simple_live_app/lib/modules/home/home_controller.dart, simple_live_app/lib/modules/indexed/indexed_controller.dart, simple_live_app/lib/modules/user/follow_user/follow_user_controller.dart, simple_live_app/pubspec.yaml, simple_live_core/example/simple_live_core_example.dart, simple_live_core/lib/src/douyu_site.dart
=> Release 1.2.4

.github/workflows/publish_app_release.yml, assets/app_version.json, simple_live_app/lib/app/log.dart, simple_live_app/lib/modules/live_room/live_room_page.dart, simple_live_app/pubspec.yaml, simple_live_console/pubspec.lock, simple_live_core/lib/src/common/core_log.dart, simple_live_core/pubspec.yaml
1. 修改直播间黑屏问题 #125
2. 更新Flutter版本至3.13.5
=> Release 1.3.3

.github/workflows/publish_app_release.yml, assets/app_version.json, simple_live_app/android/app/src/main/AndroidManifest.xml, simple_live_app/lib/app/constant.dart, simple_live_app/lib/app/sites.dart, simple_live_app/lib/app/utils.dart, simple_live_app/lib/modules/live_room/live_room_controller.dart, simple_live_app/lib/modules/live_room/live_room_page.dart, simple_live_app/lib/modules/live_room/player/player_controller.dart, simple_live_app/lib/modules/live_room/player/player_controls.dart, simple_live_app/lib/modules/toolbox/toolbox_controller.dart, simple_live_app/lib/modules/user/follow_user/follow_user_controller.dart, simple_live_app/lib/modules/user/follow_user/follow_user_page.dart, simple_live_app/lib/modules/user/history/history_page.dart, simple_live_app/lib/modules/user/user_page.dart, simple_live_app/lib/routes/app_pages.dart, simple_live_app/lib/widgets/filter_button.dart, simple_live_app/lib/widgets/follow_user_item.dart, simple_live_app/pubspec.yaml, simple_live_core/example/simple_live_core_example.dart, simple_live_core/lib/src/bilibili_site.dart, simple_live_core/lib/src/danmaku/bilibili_danmaku.dart
1. ~~修复哔哩哔哩用户名隐藏问题 #150~~ 无效
2. 修复修改平台排序后链接解析失败 #156
3. Android平台支持小窗播放 #157, #13
4. 关注列表支持按状态筛选主播
5. 支持将关注列表导出为文本
6. 直播间内可快速切换关注的直播间
7. 直播间内可设置屏蔽关键词 #153
8. 全屏播放器手势限制滑动区域防误操作 #129
=> Release 1.4.0

assets/app_version.json, simple_live_app/lib/modules/live_room/live_room_page.dart, simple_live_app/lib/modules/live_room/player/player_controller.dart, simple_live_app/lib/modules/live_room/player/player_controls.dart, simple_live_app/pubspec.yaml
1. 修复播放器全屏时点击问题 #168 
2. 修改播放器缓冲区大小
=> Release 1.4.1

assets/app_version.json, simple_live_app/ios/Runner.xcodeproj/project.pbxproj, simple_live_app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, simple_live_app/lib/modules/user/account/bilibili/web_login_controller.dart, simple_live_app/lib/modules/user/account/bilibili/web_login_page.dart, simple_live_app/pubspec.yaml
=> Release 1.4.4

.github/workflows/publish_app_dev.yaml
This pull request adds automated nightly builds to the project. The workflows can be triggered manually or automatically on push events to `dev` branch. Artifacts will not be published to GitHub releases.
=> proj(ci): create nightly/dev workflows

.github/workflows/publish_app_dev.yaml, .github/workflows/publish_app_release.yml, assets/app_version.json, simple_live_app/lib/app/controller/app_settings_controller.dart, simple_live_app/lib/app/custom_throttle.dart, simple_live_app/lib/app/utils.dart, simple_live_app/lib/modules/live_room/live_room_controller.dart, simple_live_app/lib/modules/live_room/player/player_controller.dart, simple_live_app/lib/modules/user/danmu_shield/danmu_shield_page.dart, simple_live_app/lib/modules/user/play_settings_page.dart, simple_live_app/lib/services/local_storage_service.dart, simple_live_app/pubspec.yaml, simple_live_core/lib/src/douyin_site.dart
- 修复抖音内容加载失败问题 #285
- iOS放开后台播放设置
- 修复音量拖动调节时卡顿问题 #92 (#294 @abcghy)
- 弹幕支持使用正则屏蔽 #283 (#295 @abcghy)
- 定时关闭建议记忆上次设定的时长 #278 (#296 @abcghy)
=> Release 1.4.8

simple_live_app/lib/app/utils.dart, simple_live_app/lib/modules/live_room/live_room_controller.dart, simple_live_app/lib/modules/user/danmu_shield/danmu_shield_page.dart
=> [feat] add regex feature for danmu filter

simple_live_app/lib/app/controller/app_settings_controller.dart, simple_live_app/lib/modules/live_room/live_room_controller.dart, simple_live_app/lib/services/local_storage_service.dart
=> [feat] remember standalone auto exit duration for single Room

assets/app_version.json, simple_live_app/lib/modules/live_room/live_room_controller.dart, simple_live_app/pubspec.yaml, simple_live_core/lib/src/huya_site.dart
=> Release 1.4.9

assets/app_version.json, assets/tv_app_version.json, simple_live_app/lib/modules/sync/sync_controller.dart, simple_live_app/lib/services/sync_service.dart, simple_live_app/pubspec.yaml, simple_live_core/lib/src/huya_site.dart, simple_live_tv_app/lib/app/utils.dart, simple_live_tv_app/lib/modules/home/home_page.dart, simple_live_tv_app/lib/modules/live_room/live_room_controller.dart, simple_live_tv_app/lib/modules/live_room/live_room_page.dart, simple_live_tv_app/lib/modules/live_room/player/player_controls.dart, simple_live_tv_app/pubspec.lock, simple_live_tv_app/pubspec.yaml
- 修复虎牙播放中断问题 #339 (#341 @lemonfog)
- 支持多端数据同步
- Linux使用mimalloc防止内存泄漏 #328 @madoka773
- 修复虎牙一起看分区两分钟时参数验证失败 (#345 @lemonfog)
=> Release 1.5.3 / TV 1.0.3

assets/app_version.json, assets/tv_app_version.json, simple_live_app/lib/app/controller/app_settings_controller.dart, simple_live_app/lib/services/local_storage_service.dart, simple_live_app/pubspec.yaml, simple_live_tv_app/lib/app/controller/app_settings_controller.dart, simple_live_tv_app/lib/services/local_storage_service.dart, simple_live_tv_app/pubspec.lock, simple_live_tv_app/pubspec.yaml
=> Release 1.7.3 / TV 1.1.9

simple_live_app/lib/app/app_style.dart, simple_live_app/lib/app/controller/app_settings_controller.dart, simple_live_app/lib/modules/live_room/live_room_controller.dart, simple_live_app/lib/modules/live_room/live_room_page.dart, simple_live_app/lib/modules/live_room/player/player_controller.dart, simple_live_app/lib/modules/settings/play_settings_page.dart, simple_live_app/lib/services/local_storage_service.dart, simple_live_app/pubspec.yaml, simple_live_core/lib/src/huya_site.dart, simple_live_tv_app/pubspec.yaml
- 修复虎牙一起看播放失败 #543 
- 支持强制使用https链接播放 #538
- 仅在播放时保持亮屏 #541
- Windows字体使用微软雅黑 #535
=> Release 1.7.4 / TV 1.2.0

simple_live_app/lib/modules/live_room/live_room_controller.dart
from here: https://github.com/stream-rec/stream-rec/commits/dev/
=> Fix(虎牙断流)：increase ua version. Fixes #585

simple_live_app/lib/modules/sync/remote_sync/room/remote_sync_room_controller.dart, simple_live_tv_app/lib/modules/sync/sync_controller.dart
=> 修复屏蔽词列表同步失败 Fixes #619

assets/tv_app_version.json, simple_live_tv_app/pubspec.yaml
回滚，修复：#652，#649，#647，#646 ，#643
=> Release TV 1.2.5

simple_live_core/lib/src/huya_site.dart
更新 user-agent 的时间戳计算方式 fix: #700
=> 更新 user-agent 的时间戳计算方式 fix: #700

simple_live_app/lib/modules/live_room/live_room_controller.dart
=> 复制未播放直播流 #728

simple_live_app/lib/modules/mine/parse/parse_controller.dart, simple_live_app/lib/modules/mine/parse/parse_page.dart
example: https://www.douyu.com/topic/RACE2025?rid=24422&dyshid=3aee8-92b276a59778ee071d826d3700041601
=> 支持对斗鱼topic链接的解析

simple_live_core/lib/src/huya_site.dart
=> 修复虎牙播放UA问题

.vscode/settings.json, assets/app_version.json, simple_live_app/lib/models/db/follow_user.dart, simple_live_app/lib/modules/live_room/live_room_controller.dart, simple_live_app/lib/modules/live_room/live_room_page.dart, simple_live_app/lib/modules/live_room/player/player_controls.dart, simple_live_app/lib/services/follow_service.dart, simple_live_app/lib/widgets/follow_user_item.dart, simple_live_app/lib/widgets/superchat_card.dart, simple_live_core/lib/src/bilibili_site.dart, simple_live_core/lib/src/douyu_site.dart, simple_live_core/lib/src/model/live_room_detail.dart
=> 添加了开播时长的显示，现在能够在哔哩哔哩和斗鱼平台看到主播的开播时长，添加了在直播间画面中显示sc

simple_live_app/lib/services/db_service.dart, simple_live_app/lib/services/follow_service.dart
hive box为key-value 存储
但在设计tag时，存入的key为 tag.id，但在读取时候非常低级得错误的设计为tag值
=> fix(tag):tag设计导致的导入功能错误
